services:
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: /start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    links:
      - pgdb
    depends_on:
      - pgdb
    networks:
      - siecom_prod_network
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web-prod
    networks:
      - siecom_prod_network
  pgdb:
    image: postgres:17
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - siecom_prod_network
volumes:
  postgres_data_prod:
  static_volume:
networks:
  siecom_prod_network:
    driver: bridge
    name: siecom_prod_network