services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /start.sh
    volumes:
      - .:/app
      - static_volume:/home/app/staticfiles
    env_file:
      - .env
    depends_on:
      - pgdb
      - redis
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/staticfiles
  huey:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py run_huey
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - pgdb
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  pgdb:
    image: postgres:17
    volumes:
      - pgdb_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  pgdb_data:
  static_volume: