# Generated by Django 5.2.6 on 2025-09-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_created_order_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="auth0_id",
        ),
        migrations.AddField(
            model_name="user",
            name="oidc_iss",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="oidc_sub",
            field=models.CharField(db_index=True, default="", max_length=255),
        ),
    ]
