# Generated by Django 5.2.6 on 2025-09-17 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_corrected_oicd_requirements"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="oidc_iss",
            new_name="oidc_issuer",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="oidc_sub",
            new_name="oidc_subject",
        ),
    ]
