# Generated by Django 5.2.6 on 2025-09-18 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_better_naming_of_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
