# Generated by Django 5.2.6 on 2025-09-18 14:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_removed_phnumber_from_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_category_name_ci",
            ),
        ),
    ]
