# Generated by Django 5.2.6 on 2025-09-18 14:39

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_added_unique_constraint"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_product_name_ci",
            ),
        ),
    ]
