apiVersion: apps/v1
kind: Deployment
metadata:
  name: siecom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siecom
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: siecom
    spec:
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: siecom-static-pvc 
      initContainers:
        - name: migrate
          image: asininefatuity/siecom:latest
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - secretRef:
                name: siecom-secrets

        - name: collectstatic
          image: asininefatuity/siecom:latest
          command: ["python", "manage.py", "collectstatic", "--noinput", "--clear"]
          envFrom:
            - secretRef:
                name: siecom-secrets
          volumeMounts:
            - name: static-files
              mountPath: /home/app/staticfiles

      containers:
        - name: siecom
          image: asininefatuity/siecom:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: siecom-secrets
          command: ["gunicorn", "siecom.wsgi:application", "--bind", "0.0.0.0:8000"]
          volumeMounts:
            - name: static-files
              mountPath: /home/app/staticfiles

        - name: huey
          image: asininefatuity/siecom:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: siecom-secrets
          command: ["python","manage.py", "run_huey"]
          volumeMounts:
            - name: static-files
              mountPath: /home/app/staticfiles
